version: '3.3'

services:
  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_USER: dartvader
      POSTGRES_PASSWORD: "DARKSIDE!"
    ports:
      - "15432:5432"
#    env_file:
#      - database.env # configure postgres
    volumes:
      - /home/leandro/Docker-Volumes/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
    networks:
      - postgres-compose-network

  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "dartvader@sith.club"
      PGADMIN_DEFAULT_PASSWORD: "DARKSIDE!"
    ports:
      - "16543:80"
    depends_on:
      - teste-postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge